[package]
name = "rust-liveview"
version = "0.1.0"
license = "MIT"
authors = ["Philippe Lafontaine <lafontaine.philippe@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
async-std = { version = "1.4.0", features = ["unstable", "attributes"] }
async-tungstenite = "0.3.1"
derive_more = "0.99.2"
futures = "0.3.1"
thiserror = "1.0.9"

[dev-dependencies]
fluid = "0.4"